import {
  Home,
  Info,
  Briefcase,
  GraduationCap,
  Lightbulb,
  FolderOpen,
  BadgeCheck,
  Mail,
  FileText,
  Calendar,
  Notebook,
  File,
  Music,
  LogOut,
  ShoppingCartIcon,
} from "lucide-react";

const baseUrl = "https://www.elevisio.online";

const employmentType = [
  { key: "Full-time", label: "Full-time" },
  { key: "Part-time", label: "Part-time" },
  { key: "Contract", label: "Contract" },
  { key: "Internship", label: "Internship" },
  { key: "Freelance", label: "Freelance" },
  { key: "Remote", label: "Remote" },
  { key: "Temporary", label: "Temporary" },
  { key: "Casual", label: "Casual" },
  { key: "Volunteer", label: "Volunteer" },
  { key: "Self-Employed", label: "Self-Employed" },
  { key: "Apprenticeship", label: "Apprenticeship" },
  { key: "Other", label: "Other" },
];

const allowedImageTypes = ["image/png", "image/jpeg", "image/jpg", "image/gif"];

const minAge = 13;
const maxAge = 100;

const navigationItems = [
  { name: "Home", href: "/dashboard", icon: Home },
  { name: "Info", href: "/dashboard/info", icon: Info },
  { name: "Work Experience", href: "/dashboard/experience", icon: Briefcase },
  { name: "Education", href: "/dashboard/education", icon: GraduationCap },
  { name: "Skills", href: "/dashboard/skills", icon: Lightbulb },
  { name: "Projects", href: "/dashboard/projects", icon: FolderOpen },
  { name: "Certificates", href: "/dashboard/certificates", icon: BadgeCheck },
  { name: "Contact", href: "/dashboard/contact", icon: Mail },
  { name: "Blog", href: "/dashboard/blog", icon: FileText },
  { name: "Events", href: "/dashboard/events", icon: Calendar },
  { name: "Shop", href: "/dashboard/shop", icon: ShoppingCartIcon },
  { name: "Notes", href: "/dashboard/notes", icon: Notebook },
  { name: "CV", href: "/dashboard/cv", icon: File },
  { name: "Themes & Music", href: "/dashboard/themes", icon: Music },
  { name: "Logout", href: "#", icon: LogOut },
];

const techSkills = [
  "frontend-web",
  "frontend-mobile",
  "backend",
  "fullstack",
  "devops",
  "cloud-computing",
  "database",
  "data-engineering",
  "ai-ml",
  "data-science",
  "computer-vision",
  "nlp",
  "blockchain",
  "web3",
  "cryptography",
  "cybersecurity",
  "embedded-systems",
  "iot",
  "arduino",
  "raspberry-pi",
  "game-development",
  "unity",
  "unreal-engine",
  "vr-ar",
  "qa-testing",
  "automation-testing",
  "performance-testing",
  "sysadmin",
  "networking",
  "it-support",
  "technical-writing",
];

const designSkills = [
  "graphic-design",
  "ui-ux",
  "web-design",
  "mobile-design",
  "motion-graphics",
  "3d-modeling",
  "3d-animation",
  "illustration",
  "character-design",
  "typography",
  "print-design",
  "branding",
  "logo-design",
  "packaging-design",
  "photo-editing",
  "video-editing",
  "vfx",
  "color-grading",
  "sound-design",
  "music-production",
  "podcast-production",
];

const marketingSkills = [
  "seo",
  "sem",
  "social-media-marketing",
  "content-marketing",
  "email-marketing",
  "influencer-marketing",
  "affiliate-marketing",
  "growth-hacking",
  "digital-strategy",
  "market-research",
  "brand-management",
  "ppc-advertising",
  "google-ads",
  "facebook-ads",
  "video-marketing",
  "community-management",
];

const businessSkills = [
  "project-management",
  "product-management",
  "scrum-agile",
  "business-analysis",
  "business-development",
  "sales",
  "customer-success",
  "operations-management",
  "supply-chain",
  "logistics",
  "hr-management",
  "recruiting",
  "training-development",
  "financial-analysis",
  "accounting",
  "risk-management",
  "entrepreneurship",
  "startups",
  "venture-capital",
];

const creativeSkills = [
  "copywriting",
  "content-writing",
  "technical-writing",
  "scriptwriting",
  "translation",
  "editing-proofreading",
  "blogging",
  "journalism",
  "creative-writing",
  "ghostwriting",
  "voice-over",
  "presentation-skills",
  "storytelling",
  "photography",
  "cinematography",
  "documentary-filmmaking",
];

const tradeSkills = [
  "carpentry",
  "plumbing",
  "electrical",
  "welding",
  "auto-repair",
  "construction",
  "masonry",
  "roofing",
  "landscaping",
  "gardening",
  "painting",
  "interior-design",
  "tailoring",
  "fashion-design",
  "jewelry-making",
  "pottery",
];

const healthSkills = [
  "fitness-training",
  "yoga",
  "nutrition",
  "dietetics",
  "nursing",
  "massage-therapy",
  "physical-therapy",
  "mental-health",
  "counseling",
  "first-aid",
  "cpr",
  "elderly-care",
  "child-care",
  "pharmacy",
  "medical-research",
];

export {
  baseUrl,
  employmentType,
  allowedImageTypes,
  minAge,
  maxAge,
  navigationItems,
  techSkills,
  designSkills,
  marketingSkills,
  businessSkills,
  creativeSkills,
  tradeSkills,
  healthSkills,
};
