import Header from "@/components/Layout/Header";
import SideBar from "@/components/Layout/SideBar";
import { Providers } from "@/providers/Providers";
import { getUserDataDashboard } from "@/services/services";
import { User } from "@/types/userInfo.types";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default async function DashboardLayout({ children }: { children: React.ReactNode }) {
    const user: User = await getUserDataDashboard("/dashboard/global", "user-dashboard-data")
    return (
        <div className={`antialiased `}>
            <Providers>
                <Header user={user} />
                <div className="flex ">
                    <aside className="w-0 lg:w-60 lg:border-e lg:border-divider">
                        <SideBar />
                    </aside>

                    <div className=" flex-1 flex flex-col overflow-hidden">
                        <div className="md:p-4 lg:p-6  overflow-auto">
                            {children}
                        </div>
                    </div>
                </div>
            </Providers>
        </div>
    );
}